name: NodeJS Application CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Via SSH
        uses: appleboy/ssh-action@v1.0.3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          host: ${{ secrets.DOCKER_USERNAME }}
          username: root
          key: ${{ secrets.DOCKER_PASSWORD }}
          scripts: |
             cd /root/NodejS-application-CICD-pipeline
             git pull
             docker-compose up -d --build
